apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-pvc
  namespace: sonarqube
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi