apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "sonarqube-utm-242"
        - name: POSTGRES_USER
          value: "s0n4rqub3-242"
        - name: POSTGRES_PASSWORD
          value: "8&%EWYK7Jid2"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data-pvc
