apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: sonar-utm-242
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-data"