apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions
  namespace: sonarqube
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/sonar-extensions"